### ISSUE TITLE
[BUG] Name field appears in the attrs['cfg'] of the HDF5 output

### ISSUE THREAD

**Issue by francois-drielsma** [DeepLearnPhysics/spine#31]
**Describe the bug**
In the `file['info'].attrs['cfg']` field of the output HDF5 files, there are spurious `name` attributes in each of the `post` blocks that do not appear in the original configuration, e.g.:

```yaml
  topology_threshold:
    ke_thresholds:
      4: 50
      default: 25
    name: !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U18
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 72
      - 4
      - 8
    - !!binary |
      dAAAAG8AAABwAAAAbwAAAGwAAABvAAAAZwAAAHkAAABfAAAAdAAAAGgAAAByAAAAZQAAAHMAAABo
      AAAAbwAAAGwAAABkAAAA
```

**To Reproduce**
Run a SPINE `.cfg` files which contains a post-processor, and a `write` block, take a look at the output HDF5 file.

**Expected behavior**
This configuration should only contain keys which appear in the original configuration passed to SPINE.

**Code base**
Provide the following:
 - SPINE release 0.1.0+ (generalized)
