### ISSUE TITLE
[FR] reco_start_point and reco_end_point

### ISSUE THREAD

**Issue by zhulcher** [DeepLearnPhysics/spine#46]
**Is your feature request related to a problem? Please describe.**

The start and end points for truth particles are separated from their voxels by a sometimes significant distance due to being out-of-time.

**Describe the solution you'd like**

It would be nice to have "reco" start and end points which, while identical for the reco particles, incorporate the shift due to timing for truth particles to line up with the voxels of their corresponding particle. 

<img width="445" alt="Image" src="https://github.com/user-attachments/assets/d84743ef-f3bf-4cfa-bb83-5217471e1d7c" />

**Comment by francois-drielsma** [comment]
Attempted to build the true objects with the following configuration:
```
# Base configuration
base:
  iterations: -1
  unwrap: true
  overwrite_log: true

# IO configuration
io:
  loader:
    batch_size: 1
    shuffle: false
    num_workers: 0
    collate_fn: all
    dataset:
      name: larcv
      file_keys: null
      schema:
        clust_label:
          parser: cluster3d
          cluster_event: cluster3d_pcluster
          particle_event: particle_corrected
          neutrino_event: neutrino_mpv
          sparse_semantics_event: sparse3d_pcluster_semantics
          add_particle_info: true
          clean_data: true
        clust_label_g4:
          parser: cluster3d
          cluster_event: cluster3d_sed
          particle_event: particle_corrected
          add_particle_info: true
        charge_label:
          parser: sparse3d_aggr
          aggr: sum
          sparse_event_list:
            - sparse3d_reco_cryoE_rescaled
            - sparse3d_reco_cryoW_rescaled
        particles:
          parser: particle
          particle_event: particle_corrected
          neutrino_event: neutrino_mpv
          cluster_event: cluster3d_pcluster
        neutrinos:
          parser: neutrino
          neutrino_event: neutrino_mpv
          cluster_event: cluster3d_pcluster
        meta:
          parser: meta
          sparse_event: sparse3d_pcluster
        run_info:
          parser: run_info
          sparse_event: sparse3d_pcluster

  writer:
    name: hdf5
    file_name: null
    overwrite: true
    keys:
      - run_info
      - meta
      - points_label
      - points_g4
      - depositions_label
      - depositions_q_label
      - depositions_g4
      - truth_particles
      - truth_interactions

# Build output representations
build:
  mode: truth
  units: cm
  fragments: false
  particles: true
  interactions: true
```

And visualized them using the default drawing tools, could not reproduce the issue.

![Image](https://github.com/user-attachments/assets/ccaa2ae6-f80b-4a71-9fc5-02ff585ba9b9)
